### ISSUE TITLE
Filesystem API could not be initialized.

### ISSUE THREAD

**Issue by oempire** [tillkruss/Nginx-FastCGI-Cache#7]
Getting this error Filesystem API could not be initialized.

however i can upload plugins, update core, theme etc without having to supply login credentials so i dont think thats the cause.

I have the path specified as /var/cache/nginx and both have access by www-data user

**Comment by tillkruss** [comment]
Could you try the `master` of this repo, if that works?

See https://github.com/tillkruss/Nginx-FastCGI-Cache/pull/6

**Comment by siparker** [comment]
If, Like me, you are hosting this somewhere that uses a different user for PHP than the Nginx user (www-data probably?) then you will find you get a filesystem API could not be initialised error not because of anything to do with the filesystem api but because the current php user cant read and write to the nginx cache folder as its owned by a different user.

I wrote up the solution here [https://www.siparker.net/web/nginx-proxy-caching-with-multiple-php-pools-and-wordpress/](https://www.siparker.net/web/nginx-proxy-caching-with-multiple-php-pools-and-wordpress/ )
